### ISSUE TITLE
Construir formulário para sistema de RPG SavageWorlds

### ISSUE THREAD

**Issue by maickon** [maickon/HelpRpg-Fichas#2]
Link de um formulário de exemplo: https://adaptron.files.wordpress.com/2014/10/anc3a3o-sw.jpg

**Comment by SpiderCod3R** [comment]
Iniciando Desenvolvimento

**Comment by SpiderCod3R** [comment]
criando savage-worlds - commit 6daad0555b6793fb40c215e6ecd00d88e668c34d
